const siteConfig = {
  name: "Kotor Car Hire",
  tagline: "Drive the Bay of Kotor",
  domain: "kotorcarhire.com",
  phone: "",
  email: "info@kotorcarhire.com",
  address: "Kotor, Montenegro",

  hero: {
    headline: "Explore the Bay of Kotor by Car",
    subheadline: "Pick up at Tivat Airport (8 km away) or Kotor Old Town. Drive the UNESCO bay, Perast, Budva, and beyond.",
    image: "/img/hero-kotor.webp",
  },

  cars: [
    {
      id: 1,
      slug: "vw-polo",
      name: "VW Polo",
      category: "Economy",
      price: 25,
      image: "/img/pexels-1035108.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["Air Conditioning", "Bluetooth Audio", "USB Charging", "Central Locking"],
      popular: false,
    },
    {
      id: 2,
      slug: "skoda-octavia",
      name: "Skoda Octavia",
      category: "Mid-Size",
      price: 35,
      image: "/img/pexels-116675.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 4,
      ac: true,
      features: ["Automatic Transmission", "Cruise Control", "Parking Sensors", "Large Boot"],
      popular: true,
    },
    {
      id: 3,
      slug: "toyota-corolla",
      name: "Toyota Corolla",
      category: "Mid-Size",
      price: 38,
      image: "/img/pexels-170811.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Hybrid",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Hybrid Engine", "Reversing Camera", "Apple CarPlay", "Keyless Start"],
      popular: false,
    },
    {
      id: 4,
      slug: "mercedes-c-class",
      name: "Mercedes C-Class",
      category: "Premium",
      price: 65,
      image: "/img/pexels-120049.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Leather Seats", "Navigation System", "Premium Sound", "Heated Seats"],
      popular: true,
    },
    {
      id: 5,
      slug: "jeep-renegade",
      name: "Jeep Renegade",
      category: "SUV",
      price: 55,
      image: "/img/pexels-1638459.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["4x4 Drive", "Hill Descent Control", "Roof Rails", "Off-Road Mode"],
      popular: false,
    },
    {
      id: 6,
      slug: "bmw-x3",
      name: "BMW X3",
      category: "Premium SUV",
      price: 85,
      image: "/img/pexels-892522.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 4,
      ac: true,
      features: ["Panoramic Roof", "Adaptive Cruise", "360 Camera", "Sport Mode"],
      popular: false,
    },
    {
      id: 7,
      slug: "fiat-500",
      name: "Fiat 500",
      category: "City",
      price: 20,
      image: "/img/pexels-1007410.jpg",
      seats: 4,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 2,
      luggage: 1,
      ac: true,
      features: ["Compact Size", "Easy Parking", "Sunroof", "Bluetooth"],
      popular: false,
    },
    {
      id: 8,
      slug: "vw-transporter",
      name: "VW Transporter",
      category: "Van",
      price: 70,
      image: "/img/pexels-2533092.jpg",
      seats: 9,
      transmission: "Manual",
      fuel: "Diesel",
      doors: 4,
      luggage: 6,
      ac: true,
      features: ["9 Seats", "Airport Shuttle Ready", "Sliding Doors", "Ample Storage"],
      popular: false,
    },
  ],

  features: [
    { icon: "map-pin", title: "Tivat Airport Pickup", description: "We meet you at Tivat arrivals, just 8 km from the Old Town walls. Drive the bay road into Kotor in 15 minutes — no shuttle, no waiting around." },
    { icon: "shield-check", title: "Full Insurance", description: "Zero excess option available. Whether you're navigating the narrow lanes inside the Old Town or the Lovcen hairpins above, you're fully covered." },
    { icon: "clock", title: "24/7 Support", description: "Stuck behind a cruise bus on the bay road? Unsure about the Tabacina car park? Call us any time — we know every metre of these roads." },
    { icon: "ban", title: "No Hidden Fees", description: "One transparent price covers insurance, VAT, and mileage. What you see when you book is exactly what you pay at pickup — nothing added at the desk." },
    { icon: "refresh-cw", title: "Free Cancellation", description: "Cruise schedule moved? Lovcen road closed by weather? Cancel up to 7 days before collection for a full refund, no questions asked." },
    { icon: "globe", title: "Cross-Border", description: "Dubrovnik is 2 hours via the Debeli Brijeg crossing — Green Card ready at pickup. Bosnia and Albania also permitted with advance notice." },
  ],

  testimonials: [
    { name: "Fiona & Callum", location: "Edinburgh, Scotland", text: "The bay road between Kotor and Perast is one of the most beautiful drives we've ever done. We stopped at every layby and took the boat out to Our Lady of the Rocks. Having the car meant we did it entirely on our own schedule. Easy pickup at Tivat and the whole process was smooth from start to finish.", rating: 5, avatar: "/img/avatar-1.webp" },
    { name: "Marcus Webb", location: "Toronto, Canada", text: "Came to Kotor specifically to climb San Giovanni fortress and drive up to Lovcen. The car was ready at Tivat arrivals before I'd even found the exit. The serpentine road to the mausoleum is unlike anything I've driven in North America — steep, narrow, spectacular. Would book again without hesitation.", rating: 5, avatar: "/img/avatar-2.webp" },
    { name: "De Vries Family", location: "Amsterdam, Netherlands", text: "Our cruise docked at Kotor and we picked up the car right at the port area. Three days of day trips — Budva, Perast, and up to the Cetinje monastery. Kids loved the island boat in Perast. The team sorted the paperwork quickly and the car seat was already fitted when we arrived.", rating: 5, avatar: "/img/avatar-3.webp" },
  ],

  faq: [
    { q: "What documents do I need?", a: "Bring your driving licence, passport, and a physical credit card in the main driver's name. If your licence doesn't display Latin-script details, an International Driving Permit is also required." },
    { q: "Can I drive to Croatia or Albania?", a: "Croatia is 2 hours away via the Debeli Brijeg border crossing — we prepare the Green Card at booking. Albania requires separate Green Card paperwork, so let us know in advance. Bosnia, Serbia, and Kosovo are also permitted." },
    { q: "Is there a minimum age?", a: "Drivers must be at least 21 with a minimum of 2 years' experience. A young driver supplement applies for those under 25 — the exact amount varies by vehicle and is shown in the search results." },
    { q: "What's included in the price?", a: "Third Party Liability and CDW insurance are included in the base price for all vehicles, along with VAT and the mandatory safety kit. Unlimited mileage is available on most cars — check the vehicle card before booking." },
    { q: "How does pickup work at Tivat Airport?", a: "Your agent meets you in the Tivat Airport arrivals hall holding a sign with your name. The car is parked directly outside. From the terminal to the Kotor Old Town walls takes around 15 minutes along the bay road. Alternatively, we can arrange pickup at the Tabacina car park at Kotor's Old Town entrance." },
    { q: "Can I drop off at a different location?", a: "One-way rentals are available across 28 pickup and dropoff points in Montenegro. Select different locations at the booking stage and a one-way fee may apply depending on the distance." },
    { q: "Can I cancel my booking?", a: "Free cancellation is available up to 7 days before the rental start date. Luxury cars and convertibles require 30 days' notice. A 6% payment processing fee is applied to all cancellations regardless of timing." },
    { q: "Is a deposit required?", a: "Most vehicles require a deposit of €100–€350 held on a physical credit card in the driver's name. Some budget cars are available with no deposit — these are clearly flagged in the search results. The hold is released when the vehicle is returned undamaged." },
    { q: "What happens if I exceed the mileage limit?", a: "Vehicles with mileage restrictions charge a per-kilometre rate above the agreed limit. The exact rate is listed in the vehicle details before you confirm your booking." },
    { q: "Are there hidden costs?", a: "No. The price shown includes all taxes and fees. There are no airport surcharges, no fuel-policy surprises, and nothing added at the desk." },
    { q: "How much is the down payment?", a: "A deposit of 15–20% of the total rental cost is required to confirm your booking. The remaining balance is settled directly with the rental agent when you collect the car." },
    { q: "Can I rent without a credit card?", a: "A small number of vehicles in the fleet are available without a credit card. These options are clearly marked in the search results when you filter by pickup location." },
  ],

  locations: [
    { name: "Tivat Airport", tag: "Most Popular" },
    { name: "Kotor Old Town", tag: "Local Pickup" },
    { name: "Budva", tag: "" },
    { name: "Perast", tag: "" },
    { name: "Tivat", tag: "" },
    { name: "Herceg Novi", tag: "" },
  ],

  destinations: [
    {
      name: "Tivat Airport",
      slug: "tivat-airport",
      tag: "Most Popular",
      desc: "Just 8 km from Kotor. We meet you at arrivals.",
      image: "/img/tivat-airport.webp",
    },
    {
      name: "Kotor",
      slug: "kotor",
      tag: "UNESCO Old Town",
      desc: "Medieval walled city and cruise port on the bay.",
      image: "/img/kotor-old-town.webp",
    },
    {
      name: "Perast",
      slug: "perast",
      tag: "15 min from Kotor",
      desc: "Baroque village and Our Lady of the Rocks.",
      image: "/img/perast-village.webp",
    },
    {
      name: "Budva",
      slug: "budva",
      tag: "30 min from Kotor",
      desc: "Riviera beaches and vibrant old town.",
      image: "/img/budva-from-kotor.webp",
    },
    {
      name: "Tivat",
      slug: "tivat",
      tag: "20 min from Kotor",
      desc: "Porto Montenegro marina and Boka Bay.",
      image: "/img/porto-montenegro.webp",
    },
    {
      name: "Podgorica Airport",
      slug: "podgorica-airport",
      tag: "Capital Hub",
      desc: "Montenegro's main international airport.",
      image: "/img/podgorica-airport.webp",
    },
    {
      name: "Dubrovnik Airport",
      slug: "dubrovnik-airport",
      tag: "Cross-Border",
      desc: "Fly into Dubrovnik, drive to Kotor in 2 hours.",
      image: "/img/dubrovnik-nearby.webp",
    },
    {
      name: "Podgorica",
      slug: "podgorica",
      tag: "Capital City",
      desc: "Montenegro's capital — gateway to the interior.",
      image: "/img/podgorica-city.webp",
    },
  ],
};

export default siteConfig;
