const siteConfig = {
  name: "Kotor Car Hire",
  tagline: "Drive the Bay of Kotor",
  domain: "kotorcarhire.com",
  phone: "",
  email: "info@kotorcarhire.com",
  address: "Tabacina BB, Kotor, 85330",

  hero: {
    headline: "Explore the Bay of Kotor by Car",
    subheadline: "Pick up at Tivat Airport (8 km away) or Kotor Old Town. Drive the bay, Perast, Budva, and beyond.",
    image: "/img/hero-kotor.webp",
  },

  cars: [
    {
      id: 1,
      slug: "vw-polo",
      typeGroup: "economy",
      name: "VW Polo",
      category: "Economy",
      tagline: "Compact hatchback for narrow streets and tight parking around the Old Town",
      lede: "Four metres of hatchback that slips into Tabacina's ground-floor bays on a busy July afternoon and still has the legs for a Lovćen run before sundown.",
      price: 25,
      image: "/img/fleet/vw-polo.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["Air Conditioning", "Bluetooth Audio", "USB Charging", "Central Locking"],
      details: {
        engine: "1.0 L TSI 3-cyl turbo petrol",
        power: "95 hp",
        consumption: "5.2 L/100 km",
        bootSize: "351 L",
        length: "4,074 mm",
        topSpeed: "187 km/h",
        acceleration: "10.8s (0\u2013100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: true,
      bestFor: ["Couples", "Cruise day-hires", "Bay-road first-timers"],
      suitability: "Two travellers with cabin bags picking up at Tivat and basing in Kotor Old Town \u2014 the Polo is the most parkable petrol hatch on the fleet.",
      regional: "Slots into the Tabacina bays under €1.50/h, threads the single waterfront lane at Perast, and holds 100 km/h on the Sozina approach without flagging. Four-cylinder petrol is the right choice for drivers who want to tuck in somewhere tight at the end of each day.",
    },
    {
      id: 2,
      slug: "fiat-500",
      typeGroup: "economy",
      name: "Fiat 500",
      category: "City",
      tagline: "Postcard citycar sized for the bastion gates and bay-road laybys",
      lede: "Parks where nothing else fits \u2014 ideal for four-night stays inside Kotor, Perast or the Dobrota waterfront.",
      price: 20,
      image: "/img/fleet/fiat-500.jpg",
      seats: 4,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 2,
      luggage: 1,
      ac: true,
      features: ["Compact Size", "Easy Parking", "Sunroof", "Bluetooth"],
      details: {
        engine: "1.0 L mild-hybrid petrol",
        power: "70 hp",
        consumption: "5.4 L/100 km",
        bootSize: "185 L",
        length: "3,571 mm",
        topSpeed: "167 km/h",
        acceleration: "13.8s (0\u2013100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: false,
      bestFor: ["Cruise passengers", "Solo travellers", "Photographers"],
      suitability: "One or two travellers whose Bay of Kotor is short hops between photo stops \u2014 Kotor to Perast, Dobrota to Prčanj, and back before sunset.",
      regional: "Fits the waterfront pull-ins between Kotor and Perast where a Golf cannot, sunroof open on the bend-17 viewpoint above Dobrota, boot just big enough for a tripod and a coolbag. Underpowered for the Lovćen serpentine in summer \u2014 stay coastal and the 500 charms.",
    },
    {
      id: 3,
      slug: "peugeot-208",
      typeGroup: "economy",
      name: "Peugeot 208",
      category: "Economy",
      tagline: "Sharp French steering for the Lovćen switchbacks \u2014 eager through the 25 hairpins",
      lede: "Small wheel, tall dash, firmer ride than a Clio \u2014 the small hatch most rewarded by Kotor's mountain road.",
      price: 29,
      image: "/img/fleet/peugeot-208.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["i-Cockpit", "Apple CarPlay", "USB Charging", "Rear Parking Sensors"],
      details: {
        engine: "1.2 PureTech 3-cyl petrol",
        power: "100 hp",
        consumption: "5.2 L/100 km",
        bootSize: "311 L",
        length: "4,055 mm",
        topSpeed: "188 km/h",
        acceleration: "10.8s (0\u2013100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: false,
      bestFor: ["Drivers who actually enjoy driving", "Couples", "Lovćen day-trippers"],
      suitability: "Couples whose Kotor trip leans on the old Austrian road \u2014 the 208 is the sharpest small hatch in the fleet through the 25 hairpins above the bay.",
      regional: "Eager through the Lovćen switchbacks between Kotor and Njeguši, keen on the short motorway hops to Budva, and the small steering wheel feels purpose-built for tight Montenegrin corners. Boot is tighter than a Polo \u2014 pack light if you're loading the whole family.",
    },
    {
      id: 4,
      slug: "citroen-c3",
      typeGroup: "economy",
      name: "Citroen C3",
      category: "Economy",
      tagline: "Softest-riding small hatch on the bay \u2014 absorbs the patched tarmac past Risan",
      lede: "Long-travel suspension, deep-foam seats \u2014 the C3 smothers surface breaks other B-segment cars fight.",
      price: 27,
      image: "/img/fleet/citroen-c3.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["Advanced Comfort Seats", "Bluetooth Audio", "USB Charging", "Lane Departure Warning"],
      details: {
        engine: "1.2 PureTech 3-cyl petrol",
        power: "83 hp",
        consumption: "5.5 L/100 km",
        bootSize: "300 L",
        length: "3,996 mm",
        topSpeed: "175 km/h",
        acceleration: "13.7s (0\u2013100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: false,
      bestFor: ["Older travellers", "Comfort-first renters", "Slow-drive back-road explorers"],
      suitability: "Anyone whose Kotor week favours slow waterfront konobas over tight deadlines \u2014 the C3 is the most comfortable small car the Bay rents out.",
      regional: "The ride lets you tackle the patched tarmac out to Risan and the Hypnos mosaics without your fillings rattling, and the high, cushioned seats suit cruise passengers whose shore day ends on the Tabacina benches. Underpowered on the Lovćen climb \u2014 if you're on a tight cruise clock, pick harder.",
    },
    {
      id: 5,
      slug: "toyota-yaris",
      typeGroup: "economy",
      name: "Toyota Yaris",
      category: "Economy",
      tagline: "Cheapest car to fuel on the bay \u2014 the hybrid sips petrol at €1.50/L",
      lede: "3.8 L/100 km real-world. The Yaris Hybrid crawls through Kotor traffic in electric mode, then glides the bay road without waking the engine.",
      price: 34,
      image: "/img/fleet/toyota-yaris.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Hybrid",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["Hybrid Drivetrain", "Reversing Camera", "Apple CarPlay", "Adaptive Cruise"],
      details: {
        engine: "1.5 VVT-i Hybrid petrol\u2013electric",
        power: "116 hp combined",
        consumption: "3.8 L/100 km",
        bootSize: "286 L",
        length: "3,940 mm",
        topSpeed: "175 km/h",
        acceleration: "9.7s (0\u2013100 km/h)",
        driveType: "Front-wheel drive (e-CVT)",
      },
      popular: true,
      bestFor: ["Fuel-conscious long-stay visitors", "Urban-weighted trips", "Cruise morning shore hires"],
      suitability: "Travellers running two weeks on a single tank of thinking \u2014 the Hybrid pays for itself on the daily Kotor\u2013Perast\u2013Risan loop.",
      regional: "Pure-electric crawl through the morning school traffic at the Škaljari bypass, then glides up the bay road to Perast without touching the fuel needle. Not the car for Žabljak runs \u2014 the small battery drains on the long climbs \u2014 but for a week on the bay it's quietly remarkable.",
    },
    {
      id: 6,
      slug: "kia-stonic",
      typeGroup: "suv",
      name: "Kia Stonic",
      category: "Compact Crossover",
      tagline: "Raised ride height without the rental SUV premium \u2014 the Njeguši back-road compromise",
      lede: "352-litre boot, higher hip point, modest 1.0-litre petrol \u2014 the crossover for unsealed spurs off the Lovćen road.",
      price: 40,
      image: "/img/fleet/kia-stonic.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Raised Ride Height", "Apple CarPlay", "Reversing Camera", "Lane Keep Assist"],
      details: {
        engine: "1.0 T-GDi 3-cyl turbo petrol",
        power: "100 hp",
        consumption: "5.5 L/100 km",
        bootSize: "352 L (1,155 L seats folded)",
        length: "4,140 mm",
        topSpeed: "183 km/h",
        acceleration: "10.7s (0\u2013100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: false,
      bestFor: ["Couples heading inland", "Shoulder-season travellers", "Budget crossover renters"],
      suitability: "Renters whose Kotor days include the Krstac shortcut off the old Austrian road, or the gravel approach to Kapetanovo Lake \u2014 higher than a hatch without SUV-tier fuel bills.",
      regional: "The extra ride height clears the unsealed final kilometre below Njeguši village, the pothole-pocked detour to upper Stoliv, and the broken waterfront verges north of Risan. Front-wheel drive only \u2014 pick this for unsealed roads in dry conditions, not for a January run up to Žabljak.",
    },
    {
      id: 7,
      slug: "vw-golf",
      typeGroup: "midsize",
      name: "VW Golf",
      category: "Mid-Size",
      tagline: "The DSG-diesel benchmark \u2014 unfussed on bay road, motorway or Lovćen climb",
      lede: "Polo's parkable footprint meets Passat-grade refinement \u2014 the rational default for trips that mix coast and mountain.",
      price: 42,
      image: "/img/fleet/vw-golf.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["DSG Automatic", "Adaptive Cruise", "Digital Cockpit", "Apple CarPlay"],
      details: {
        engine: "2.0 L TDI diesel (Mk8)",
        power: "150 hp",
        consumption: "4.3 L/100 km",
        bootSize: "381 L (1,237 L seats folded)",
        length: "4,287 mm",
        topSpeed: "223 km/h",
        acceleration: "8.4s (0\u2013100 km/h)",
        driveType: "Front-wheel drive, 7-spd DSG auto",
      },
      popular: false,
      bestFor: ["Couples mixing city and country", "Cross-border day-trippers", "Airport-to-bay transfers"],
      suitability: "Couples whose Kotor base anchors day-trips to Dubrovnik, Mostar or Žabljak \u2014 the Golf handles the cross-border push without demanding an SUV's footprint.",
      regional: "Threads the Vrmac tunnel and the Kamenari\u2013Lepetane ferry approach with the composure of something bigger, returns 4.3 L/100 km on the Debeli Brijeg run to Dubrovnik, and the DSG reads the Lovćen hairpins without you touching the gear lever. Firmer ride than a C3 on broken back roads \u2014 a fair trade for motorway calm.",
    },
  ],

  features: [
    { icon: "map-pin", title: "Tivat Airport Pickup", description: "Pick up at Tivat arrivals, just 8 km from the Old Town walls — the supplier meets you with your name on a sign and you're on the bay road into Kotor in minutes." },
    { icon: "shield-check", title: "Insurance Options", description: "Free Minimum (third-party) cover on every booking — Basic from €8/day, Full from €10/day, no-deposit Full Plus from €18/day." },
    { icon: "clock", title: "24/7 Booking Support", description: "Booking help around the clock for the bay-road drive into Kotor; roadside assistance is provided by the rental supplier." },
    { icon: "ban", title: "No Credit Card Needed", description: "Every car on the platform is bookable without a credit card — pay by cash, debit card or crypto at the supplier." },
    { icon: "refresh-cw", title: "Free Cancellation", description: "On selected cars (around 46% of the fleet): refund of advance payment if you cancel more than 24 hours before pickup." },
    { icon: "globe", title: "Cross-Border", description: "Paid cross-border permit at three tiers — neighbours, including Albania & Kosovo, or all-EU + Switzerland. Dubrovnik is 2 hours via the Debeli Brijeg crossing." },
  ],

  testimonials: [
    { name: "Fiona & Callum", location: "Edinburgh, Scotland", text: "Booked a compact for Tivat in two clicks, met by the supplier at arrivals, and on the bay road to Kotor in minutes. Drove the whole coast down to Perast and Our Lady of the Rocks on our own schedule.", rating: 5, avatar: "/img/avatar-1.webp" },
    { name: "Marcus Webb", location: "Toronto, Canada", text: "Came to Kotor specifically to climb San Giovanni fortress and drive up to Lovcen. The car was ready at Tivat arrivals before I'd even found the exit. The serpentine road to the mausoleum is unlike anything I've driven in North America, steep, narrow, spectacular. Would book again without hesitation.", rating: 5, avatar: "/img/avatar-2.webp" },
    { name: "De Vries Family", location: "Amsterdam, Netherlands", text: "Our cruise docked at Kotor and we picked up the car right at the port area. Three days of day trips, Budva, Perast, and up to the Cetinje monastery. Kids loved the island boat in Perast. The supplier sorted the paperwork quickly and the car seat was already fitted when we arrived.", rating: 5, avatar: "/img/avatar-3.webp" },
  ],

  faq: [
    { q: "Can I drop off at a different location?", a: "Yes, one-way rentals are supported across 28+ delivery points in Montenegro. Choose different pickup and dropoff locations during booking; some routes carry a small relocation fee." },
    { q: "What documents do I need?", a: "A valid driving licence and passport or ID. Most cars accept cash, debit card or crypto for payment — a credit card is not required on any booking on the platform. International Driving Permit may be needed for non-EU licences depending on the supplier." },
    { q: "Can I drive to Croatia, Albania or Italy?", a: "Yes — cross-border travel is sold as a paid permit at three tiers: (1) Croatia, Bosnia & Herzegovina and Serbia (no Green Card needed); (2) the same plus Albania and Kosovo (Green Card provided); (3) Albania, Kosovo, Croatia, Bosnia, Serbia, Macedonia, all EU countries and Switzerland (Green Card provided). The right tier for your trip is shown at checkout." },
    { q: "Is there a minimum age?", a: "Age and required driving experience vary by vehicle. The lowest cars on the platform are available from 18+ years old with 1+ years driving experience." },
    { q: "What's included in the price?", a: "Every booking includes the free Minimum (third-party liability) cover with a typical €100 deposit and VAT. Insurance upgrades are paid extras: Basic from €8/day, Full from €10/day, and a no-deposit Full Plus from €18/day. Unlimited mileage is included on most cars (376 of around 380)." },
    { q: "How does pickup work at Tivat Airport?", a: "The supplier meets you in the Tivat Airport arrivals hall with your name on a sign and walks you to the car. From the terminal to the Kotor Old Town walls takes around 15 minutes along the bay road. Pickup at the Tabacina car park at Kotor's Old Town entrance is also available." },
    { q: "Can I cancel my booking?", a: "Free cancellation is available on selected cars (around 176 of approximately 380, marked clearly in the search results). On those cars, the full advance payment is refunded if you cancel more than 24 hours before pickup; cancellations within 24 hours of pickup are non-refundable." },
    { q: "Is a deposit required?", a: "Most cars hold a €100 deposit at pickup. 47 cars on the platform require no deposit at all, and a further 124 offer a no-deposit option as a paid service. Choosing the Full Plus insurance tier (from €18/day) also waives the deposit." },
    { q: "What happens if I exceed the mileage limit?", a: "Unlimited mileage is included on the vast majority of cars (376 of ~380). For the few cars with a mileage limit, an additional charge per extra kilometre applies — shown on the listing before you book." },
    { q: "Are there hidden costs?", a: "The price you see at checkout includes the rental, your chosen insurance tier and any extras you add. Optional paid add-ons (insurance upgrades, child seats from €14, theft protection from €14, personal accident insurance from €14, cross-border permit, winter pack, etc.) are all selected by you before payment — nothing is added later." },
    { q: "How much is the down payment?", a: "An advance payment is taken when you confirm the booking; the remaining balance is paid to the supplier at pickup. The exact split is shown on each car's checkout page before you commit." },
    { q: "Can I rent without a credit card?", a: "Yes — every car on the platform can be booked without a credit card. Cash, debit card and crypto are accepted at the supplier." },
  ],

  locations: [
    { name: "Tivat Airport", tag: "Meet & Greet" },
    { name: "City Delivery", tag: "Hotel & Address" },
    { name: "Kotor Port", tag: "Cruise Pickup" },
    { name: "Bus Terminal", tag: "" },
    { name: "Kameija Mall", tag: "" },
    { name: "Hotel Forza Mare", tag: "" },
  ],

  destinations: [
    {
      name: "Tivat Airport",
      slug: "tivat-airport",
      tag: "Most Popular",
      desc: "Just 8 km from Kotor. We meet you at arrivals.",
      image: "/img/tivat-airport.webp",
    },
    {
      name: "Kotor",
      slug: "kotor",
      tag: "Old Town",
      desc: "Medieval walled city and cruise port on the bay.",
      image: "/img/kotor-old-town.webp",
    },
    {
      name: "Perast",
      slug: "perast",
      tag: "15 min from Kotor",
      desc: "Baroque village and Our Lady of the Rocks.",
      image: "/img/perast-village.webp",
    },
    {
      name: "Budva",
      slug: "budva",
      tag: "30 min from Kotor",
      desc: "Riviera beaches and vibrant old town.",
      image: "/img/budva-from-kotor.webp",
    },
    {
      name: "Tivat",
      slug: "tivat",
      tag: "20 min from Kotor",
      desc: "Porto Montenegro marina and Boka Bay.",
      image: "/img/porto-montenegro.webp",
    },
    {
      name: "Podgorica Airport",
      slug: "podgorica-airport",
      tag: "Capital Hub",
      desc: "Montenegro's main international airport.",
      image: "/img/podgorica-airport.webp",
    },
    {
      name: "Dubrovnik Airport",
      slug: "dubrovnik-airport",
      tag: "Cross-Border",
      desc: "Fly into Dubrovnik, drive to Kotor in 2 hours.",
      image: "/img/dubrovnik-nearby.webp",
    },
    {
      name: "Podgorica",
      slug: "podgorica",
      tag: "Capital City",
      desc: "Montenegro's capital, gateway to the interior.",
      image: "/img/podgorica-city.webp",
    },
    {
      name: "Herceg Novi",
      slug: "herceg-novi",
      tag: "Bay entrance",
      desc: "Coastal town at the mouth of the Bay, hour drive from Kotor.",
      image: "/img/pexels-29071814.jpg",
    },
    {
      name: "Bar",
      slug: "bar",
      tag: "South coast",
      desc: "Mediterranean port town, two hours south of Kotor.",
      image: "/img/pexels-28674522.jpg",
    },
    {
      name: "Ulcinj",
      slug: "ulcinj",
      tag: "Albanian border",
      desc: "Sandy beaches and Ottoman old town near the Albanian frontier.",
      image: "/img/pexels-26753897.jpg",
    },
    {
      name: "Nikšić",
      slug: "niksic",
      tag: "Inland",
      desc: "Mountain-fringed brewery town, gateway to Durmitor.",
      image: "/img/pexels-9526645.jpg",
    },
  ],
};

export default siteConfig;
