const siteConfig = {
  name: "Kotor Car Hire",
  tagline: "Drive the Bay of Kotor",
  domain: "kotorcarhire.com",
  phone: "",
  email: "info@kotorcarhire.com",
  address: "Tabacina BB, Kotor, 85330",

  hero: {
    headline: "Explore the Bay of Kotor by Car",
    subheadline: "Pick up at Tivat Airport (8 km away) or Kotor Old Town. Drive the bay, Perast, Budva, and beyond.",
    image: "/img/hero-kotor.webp",
  },

  cars: [
    {
      id: 1,
      slug: "vw-polo",
      typeGroup: "economy",
      name: "VW Polo",
      category: "Economy",
      tagline: "Small-footprint hatch that slots into Kotor's south-gate bays without mirror-scrape",
      lede: "Two carry-ons, five seats, a turning circle built for the medieval lanes that feed the Sea Gate.",
      price: 25,
      image: "/img/fleet/vw-polo.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["Air Conditioning", "Bluetooth Audio", "USB Charging", "Central Locking"],
      details: {
        engine: "1.0 L TSI 3-cyl turbo petrol",
        power: "95 hp",
        consumption: "5.2 L/100 km",
        bootSize: "351 L",
        length: "4,074 mm",
        topSpeed: "187 km/h",
        acceleration: "10.8s (0\u2013100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: true,
      bestFor: ["Couples", "Cruise day-hires", "Bay-road first-timers"],
      suitability: "Two travellers with cabin bags picking up at Tivat and basing in Kotor Old Town \u2014 the Polo is the most parkable petrol hatch on the fleet.",
      regional: "Slots into the Tabacina bays under €1.50/h, threads the single waterfront lane at Perast, and holds 100 km/h on the Sozina approach without flagging. Four-cylinder petrol is the right choice for drivers who want to tuck in somewhere tight at the end of each day.",
    },
    {
      id: 2,
      slug: "fiat-500",
      typeGroup: "economy",
      name: "Fiat 500",
      category: "City",
      tagline: "Postcard citycar sized for the bastion gates and bay-road laybys",
      lede: "Parks where nothing else fits \u2014 ideal for four-night stays inside Kotor, Perast or the Dobrota waterfront.",
      price: 20,
      image: "/img/fleet/fiat-500.jpg",
      seats: 4,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 2,
      luggage: 1,
      ac: true,
      features: ["Compact Size", "Easy Parking", "Sunroof", "Bluetooth"],
      details: {
        engine: "1.0 L mild-hybrid petrol",
        power: "70 hp",
        consumption: "5.4 L/100 km",
        bootSize: "185 L",
        length: "3,571 mm",
        topSpeed: "167 km/h",
        acceleration: "13.8s (0\u2013100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: false,
      bestFor: ["Cruise passengers", "Solo travellers", "Photographers"],
      suitability: "One or two travellers whose Bay of Kotor is short hops between photo stops \u2014 Kotor to Perast, Dobrota to Prčanj, and back before sunset.",
      regional: "Fits the waterfront pull-ins between Kotor and Perast where a Golf cannot, sunroof open on the bend-17 viewpoint above Dobrota, boot just big enough for a tripod and a coolbag. Underpowered for the Lovćen serpentine in summer \u2014 stay coastal and the 500 charms.",
    },
    {
      id: 3,
      slug: "peugeot-208",
      typeGroup: "economy",
      name: "Peugeot 208",
      category: "Economy",
      tagline: "Sharp French steering for the Lovćen switchbacks \u2014 eager through the 25 hairpins",
      lede: "Small wheel, tall dash, firmer ride than a Clio \u2014 the small hatch most rewarded by Kotor's mountain road.",
      price: 29,
      image: "/img/fleet/peugeot-208.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["i-Cockpit", "Apple CarPlay", "USB Charging", "Rear Parking Sensors"],
      details: {
        engine: "1.2 PureTech 3-cyl petrol",
        power: "100 hp",
        consumption: "5.2 L/100 km",
        bootSize: "311 L",
        length: "4,055 mm",
        topSpeed: "188 km/h",
        acceleration: "10.8s (0\u2013100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: false,
      bestFor: ["Drivers who actually enjoy driving", "Couples", "Lovćen day-trippers"],
      suitability: "Couples whose Kotor trip leans on the old Austrian road \u2014 the 208 is the sharpest small hatch in the fleet through the 25 hairpins above the bay.",
      regional: "Eager through the Lovćen switchbacks between Kotor and Njeguši, keen on the short motorway hops to Budva, and the small steering wheel feels purpose-built for tight Montenegrin corners. Boot is tighter than a Polo \u2014 pack light if you're loading the whole family.",
    },
    {
      id: 4,
      slug: "citroen-c3",
      typeGroup: "economy",
      name: "Citroen C3",
      category: "Economy",
      tagline: "Softest-riding small hatch on the bay \u2014 absorbs the patched tarmac past Risan",
      lede: "Long-travel suspension, deep-foam seats \u2014 the C3 smothers surface breaks other B-segment cars fight.",
      price: 27,
      image: "/img/fleet/citroen-c3.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["Advanced Comfort Seats", "Bluetooth Audio", "USB Charging", "Lane Departure Warning"],
      details: {
        engine: "1.2 PureTech 3-cyl petrol",
        power: "83 hp",
        consumption: "5.5 L/100 km",
        bootSize: "300 L",
        length: "3,996 mm",
        topSpeed: "175 km/h",
        acceleration: "13.7s (0\u2013100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: false,
      bestFor: ["Older travellers", "Comfort-first renters", "Slow-drive back-road explorers"],
      suitability: "Anyone whose Kotor week favours slow waterfront konobas over tight deadlines \u2014 the C3 is the most comfortable small car the Bay rents out.",
      regional: "The ride lets you tackle the patched tarmac out to Risan and the Hypnos mosaics without your fillings rattling, and the high, cushioned seats suit cruise passengers whose shore day ends on the Tabacina benches. Underpowered on the Lovćen climb \u2014 if you're on a tight cruise clock, pick harder.",
    },
    {
      id: 5,
      slug: "toyota-yaris",
      typeGroup: "economy",
      name: "Toyota Yaris",
      category: "Economy",
      tagline: "Cheapest car to fuel on the bay \u2014 the hybrid sips petrol at €1.50/L",
      lede: "3.8 L/100 km real-world. The Yaris Hybrid crawls through Kotor traffic in electric mode, then glides the bay road without waking the engine.",
      price: 34,
      image: "/img/fleet/toyota-yaris.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Hybrid",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["Hybrid Drivetrain", "Reversing Camera", "Apple CarPlay", "Adaptive Cruise"],
      details: {
        engine: "1.5 VVT-i Hybrid petrol\u2013electric",
        power: "116 hp combined",
        consumption: "3.8 L/100 km",
        bootSize: "286 L",
        length: "3,940 mm",
        topSpeed: "175 km/h",
        acceleration: "9.7s (0\u2013100 km/h)",
        driveType: "Front-wheel drive (e-CVT)",
      },
      popular: true,
      bestFor: ["Fuel-conscious long-stay visitors", "Urban-weighted trips", "Cruise morning shore hires"],
      suitability: "Travellers running two weeks on a single tank of thinking \u2014 the Hybrid pays for itself on the daily Kotor\u2013Perast\u2013Risan loop.",
      regional: "Pure-electric crawl through the morning school traffic at the Škaljari bypass, then glides up the bay road to Perast without touching the fuel needle. Not the car for Žabljak runs \u2014 the small battery drains on the long climbs \u2014 but for a week on the bay it's quietly remarkable.",
    },
    {
      id: 6,
      slug: "kia-stonic",
      typeGroup: "suv",
      name: "Kia Stonic",
      category: "Compact Crossover",
      tagline: "Raised ride height without the rental SUV premium \u2014 the Njeguši back-road compromise",
      lede: "352-litre boot, higher hip point, modest 1.0-litre petrol \u2014 the crossover for unsealed spurs off the Lovćen road.",
      price: 40,
      image: "/img/fleet/kia-stonic.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Raised Ride Height", "Apple CarPlay", "Reversing Camera", "Lane Keep Assist"],
      details: {
        engine: "1.0 T-GDi 3-cyl turbo petrol",
        power: "100 hp",
        consumption: "5.5 L/100 km",
        bootSize: "352 L (1,155 L seats folded)",
        length: "4,140 mm",
        topSpeed: "183 km/h",
        acceleration: "10.7s (0\u2013100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: false,
      bestFor: ["Couples heading inland", "Shoulder-season travellers", "Budget crossover renters"],
      suitability: "Renters whose Kotor days include the Krstac shortcut off the old Austrian road, or the gravel approach to Kapetanovo Lake \u2014 higher than a hatch without SUV-tier fuel bills.",
      regional: "The extra ride height clears the unsealed final kilometre below Njeguši village, the pothole-pocked detour to upper Stoliv, and the broken waterfront verges north of Risan. Front-wheel drive only \u2014 pick this for unsealed roads in dry conditions, not for a January run up to Žabljak.",
    },
    {
      id: 7,
      slug: "vw-golf",
      typeGroup: "midsize",
      name: "VW Golf",
      category: "Mid-Size",
      tagline: "The DSG-diesel benchmark \u2014 unfussed on bay road, motorway or Lovćen climb",
      lede: "Polo's parkable footprint meets Passat-grade refinement \u2014 the rational default for trips that mix coast and mountain.",
      price: 42,
      image: "/img/fleet/vw-golf.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["DSG Automatic", "Adaptive Cruise", "Digital Cockpit", "Apple CarPlay"],
      details: {
        engine: "2.0 L TDI diesel (Mk8)",
        power: "150 hp",
        consumption: "4.3 L/100 km",
        bootSize: "381 L (1,237 L seats folded)",
        length: "4,287 mm",
        topSpeed: "223 km/h",
        acceleration: "8.4s (0\u2013100 km/h)",
        driveType: "Front-wheel drive, 7-spd DSG auto",
      },
      popular: false,
      bestFor: ["Couples mixing city and country", "Cross-border day-trippers", "Airport-to-bay transfers"],
      suitability: "Couples whose Kotor base anchors day-trips to Dubrovnik, Mostar or Žabljak \u2014 the Golf handles the cross-border push without demanding an SUV's footprint.",
      regional: "Threads the Vrmac tunnel and the Kamenari\u2013Lepetane ferry approach with the composure of something bigger, returns 4.3 L/100 km on the Debeli Brijeg run to Dubrovnik, and the DSG reads the Lovćen hairpins without you touching the gear lever. Firmer ride than a C3 on broken back roads \u2014 a fair trade for motorway calm.",
    },
  ],

  features: [
    { icon: "map-pin", title: "Tivat Airport Pickup", description: "We meet you at Tivat arrivals, just 8 km from the Old Town walls. Drive the bay road into Kotor in 15 minutes, no shuttle, no waiting around." },
    { icon: "shield-check", title: "Full Insurance", description: "Zero excess option available. Whether you're navigating the narrow lanes inside the Old Town or the Lovcen hairpins above, you're fully covered." },
    { icon: "clock", title: "24/7 Support", description: "Stuck behind a cruise bus on the bay road? Unsure about the Tabacina car park? Call us any time, we know every metre of these roads." },
    { icon: "ban", title: "No Hidden Fees", description: "One transparent price covers insurance, VAT, and mileage. What you see when you book is exactly what you pay at pickup, nothing added at the desk." },
    { icon: "refresh-cw", title: "Free Cancellation", description: "Cruise schedule moved? Lovcen road closed by weather? Cancel up to 7 days before collection for a full refund, no questions asked." },
    { icon: "globe", title: "Cross-Border", description: "Dubrovnik is 2 hours via the Debeli Brijeg crossing, Green Card ready at pickup. Bosnia and Albania also permitted with advance notice." },
  ],

  testimonials: [
    { name: "Fiona & Callum", location: "Edinburgh, Scotland", text: "The bay road between Kotor and Perast is one of the most beautiful drives we've ever done. We stopped at every layby and took the boat out to Our Lady of the Rocks. Having the car meant we did it entirely on our own schedule. Easy pickup at Tivat and the whole process was smooth from start to finish.", rating: 5, avatar: "/img/avatar-1.webp" },
    { name: "Marcus Webb", location: "Toronto, Canada", text: "Came to Kotor specifically to climb San Giovanni fortress and drive up to Lovcen. The car was ready at Tivat arrivals before I'd even found the exit. The serpentine road to the mausoleum is unlike anything I've driven in North America, steep, narrow, spectacular. Would book again without hesitation.", rating: 5, avatar: "/img/avatar-2.webp" },
    { name: "De Vries Family", location: "Amsterdam, Netherlands", text: "Our cruise docked at Kotor and we picked up the car right at the port area. Three days of day trips, Budva, Perast, and up to the Cetinje monastery. Kids loved the island boat in Perast. The team sorted the paperwork quickly and the car seat was already fitted when we arrived.", rating: 5, avatar: "/img/avatar-3.webp" },
  ],

  faq: [
    { q: "Can I drop off at a different location?", a: "One-way rentals are available across 28 pickup and dropoff points in Montenegro. Select different locations at the booking stage and a one-way fee may apply depending on the distance." },
    { q: "What documents do I need?", a: "Bring your driving licence, passport, and a physical credit card in the main driver's name. If your licence doesn't display Latin-script details, an International Driving Permit is also required." },
    { q: "Can I drive to Croatia or Albania?", a: "Croatia is 2 hours away via the Debeli Brijeg border crossing, we prepare the Green Card at booking. Albania requires separate Green Card paperwork, so let us know in advance. Bosnia, Serbia, and Kosovo are also permitted." },
    { q: "Is there a minimum age?", a: "Drivers must be at least 21 with a minimum of 2 years' experience. A young driver supplement applies for those under 25, the exact amount varies by vehicle and is shown in the search results." },
    { q: "What's included in the price?", a: "Third Party Liability and CDW insurance are included in the base price for all vehicles, along with VAT and the mandatory safety kit. Unlimited mileage is available on most cars, check the vehicle card before booking." },
    { q: "How does pickup work at Tivat Airport?", a: "Your agent meets you in the Tivat Airport arrivals hall holding a sign with your name. The car is parked directly outside. From the terminal to the Kotor Old Town walls takes around 15 minutes along the bay road. Alternatively, we can arrange pickup at the Tabacina car park at Kotor's Old Town entrance." },
    { q: "Can I cancel my booking?", a: "Free cancellation is available up to 7 days before the rental start date. Luxury cars and convertibles require 30 days' notice. A 6% payment processing fee is applied to all cancellations regardless of timing." },
    { q: "Is a deposit required?", a: "Most vehicles require a deposit of €100–€350 held on a physical credit card in the driver's name. Some budget cars are available with no deposit, these are clearly flagged in the search results. The hold is released when the vehicle is returned undamaged." },
    { q: "What happens if I exceed the mileage limit?", a: "Vehicles with mileage restrictions charge a per-kilometre rate above the agreed limit. The exact rate is listed in the vehicle details before you confirm your booking." },
    { q: "Are there hidden costs?", a: "No. The price shown includes all taxes and fees. There are no airport surcharges, no fuel-policy surprises, and nothing added at the desk." },
    { q: "How much is the down payment?", a: "A deposit of 15–20% of the total rental cost is required to confirm your booking. The remaining balance is settled directly with the rental agent when you collect the car." },
    { q: "Can I rent without a credit card?", a: "A small number of vehicles in the fleet are available without a credit card. These options are clearly marked in the search results when you filter by pickup location." },
  ],

  locations: [
    { name: "Tivat Airport", tag: "Most Popular" },
    { name: "Kotor Old Town", tag: "Local Pickup" },
    { name: "Budva", tag: "" },
    { name: "Perast", tag: "" },
    { name: "Tivat", tag: "" },
    { name: "Herceg Novi", tag: "" },
  ],

  destinations: [
    {
      name: "Tivat Airport",
      slug: "tivat-airport",
      tag: "Most Popular",
      desc: "Just 8 km from Kotor. We meet you at arrivals.",
      image: "/img/tivat-airport.webp",
    },
    {
      name: "Kotor",
      slug: "kotor",
      tag: "Old Town",
      desc: "Medieval walled city and cruise port on the bay.",
      image: "/img/kotor-old-town.webp",
    },
    {
      name: "Perast",
      slug: "perast",
      tag: "15 min from Kotor",
      desc: "Baroque village and Our Lady of the Rocks.",
      image: "/img/perast-village.webp",
    },
    {
      name: "Budva",
      slug: "budva",
      tag: "30 min from Kotor",
      desc: "Riviera beaches and vibrant old town.",
      image: "/img/budva-from-kotor.webp",
    },
    {
      name: "Tivat",
      slug: "tivat",
      tag: "20 min from Kotor",
      desc: "Porto Montenegro marina and Boka Bay.",
      image: "/img/porto-montenegro.webp",
    },
    {
      name: "Podgorica Airport",
      slug: "podgorica-airport",
      tag: "Capital Hub",
      desc: "Montenegro's main international airport.",
      image: "/img/podgorica-airport.webp",
    },
    {
      name: "Dubrovnik Airport",
      slug: "dubrovnik-airport",
      tag: "Cross-Border",
      desc: "Fly into Dubrovnik, drive to Kotor in 2 hours.",
      image: "/img/dubrovnik-nearby.webp",
    },
    {
      name: "Podgorica",
      slug: "podgorica",
      tag: "Capital City",
      desc: "Montenegro's capital, gateway to the interior.",
      image: "/img/podgorica-city.webp",
    },
  ],
};

export default siteConfig;
